In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('./csv/15_03_2023/ailey_in_person.csv', index_col=False)

In [8]:
df

,Start time,Sign up,Class Schedule,Instructor,Studio,Duration
0,6:00 pm EDT,/ASP/res_a.asp?tg=12&classId=2146822747&classD...,IN-STUDIO Beginner Ballet,Benjamin Briones,Studio 1A,1 hour & 30 minutes
1,6:30 pm EDT,/ASP/res_a.asp?tg=12&classId=2146822764&classD...,IN-STUDIO Beginner Horton,Amos Machanic,Studio 1C,1 hour & 30 minutes
2,6:30 pm EDT,/ASP/res_a.asp?tg=12&classId=2146823140&classD...,IN-STUDIO Zumba Fitness,Mike Gomez,Studio 1B,1 hour
3,7:00 pm EDT,/ASP/res_a.asp?tg=12&classId=2146822756&classD...,IN-STUDIO Beginner Heels,Marie Rose Baramo,Studio LLC,1 hour & 15 minutes
4,7:00 pm EDT,/ASP/res_a.asp?tg=12&classId=2146823822&classD...,IN-STUDIO Beginner West African,Bakary Fall,Studio 2A,1 hour & 30 minutes
5,6:30 pm EDT,/ASP/res_a.asp?tg=12&classId=2146822749&classD...,IN-STUDIO Beginner Broadway Jazz,Judine Somerville,Studio 5D,1 hour
6,6:30 pm EDT,/ASP/res_a.asp?tg=12&classId=2146823264&classD...,IN-STUDIO Open Hip-Hop,Antonio Jefferson,Studio 5A,1 hour & 30 minutes
7,7:00 pm EDT,/ASP/res_a.asp?tg=12&classId=2146822753&classD...,IN-STUDIO Beginner Contemporary,Linda Celeste Sims,Studio 5B,1 hour & 30 minutes
8,7:00 pm EDT,/ASP/res_a.asp?tg=12&classId=2146823178&classD...,IN-STUDIO Beginner Hip-Hop,Keith Alexander,Studio 2B,1 hour